### ISSUE TITLE
UI overlap when pressing "Load game" from a game over branch

### ISSUE THREAD

**Issue by eileenthg** [Colaboi2009/MagiumIllunaPrequel#1]
![Screenshot_20240824_085614_com DefaultCompany MagiumIllunaPrequel](https://github.com/user-attachments/assets/08175030-45b9-4bdc-a096-1cf63eea0af3)

Phone: Huawei Nova 7
OS: Android (EMUI 12)

**Comment by Colaboi2009** [comment]
Fixed, apologies for being so late, I didn't see these issues. The good news is that I hadn't realized because a team has formed with the author's brother, to port the original game, and in possible a few weeks or months we might add in the prequel, also writing is starting to continue the story.
