### ISSUE TITLE
Many dead ends in Chapter 3

### ISSUE THREAD

**Issue by eileenthg** [Colaboi2009/MagiumIllunaPrequel#2]
![Screenshot_20240824_090210_com DefaultCompany MagiumIllunaPrequel](https://github.com/user-attachments/assets/8b363cdb-f21a-40f0-baee-17bc9ee97e54)

Phone: Huawei Nova 7
OS: Android (EMUI 12)

Choices taken
![Screenshot_20240824_090218_com DefaultCompany MagiumIllunaPrequel](https://github.com/user-attachments/assets/6a157725-2723-4c6d-a0c2-125d89418c40)

**Comment by eileenthg** [comment]
Dead ends as in no buttons to click to continue the story. Seems only one very specific path leads to Chapter 4 and it involves not picking up the amulet in Chapter 3.

**Comment by Colaboi2009** [comment]
Fixed.
